# echo -n 'admin' | base64   >>> YWRtaW4=
# to encode : kubectl get secret activemq-admin-password -o jsonpath='{.data.password}' | base64 --decode -
apiVersion: v1
kind: Secret
metadata:
  name: activemq-admin-password 
type: Opaque
data:
   ACTIVEMQ_ADMIN_PASSWORD: YWRtaW4=