version: '3'
services:
  activemq:
    image: erhancetin/activemq
    restart: always
    container_name: activemq
    ports:
      - 61613:61613
      - 61616:61616
      - 8161:8161
    volumes:
      - ./volumes/log/activemq:/var/log/activemq
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
      - ACTIVEMQ_CONFIG_MINMEMORY=512
      - ACTIVEMQ_CONFIG_MAXMEMORY=1024
    networks:
      - news-tracker-network
  newsproducer:
    image: erhancetin/k8s-news-tracker-job
    restart: on-failure
    container_name: newsproducer
    environment:
     - NEWSAPI_AUTHORIZATION=db87162d00af4d1bb4c8031ad1cf22f5
     - ACTIVEMQ_HOST=activemq
     - ACTIVEMQ_PORT=61613
     - ACTIVEMQ_QUEUE_NAME=news-queue
     - ACTIVEMQ_USER_LOGIN=admin
     - ACTIVEMQ_USER_PASSWORD=admin
     - ACTIVEMQ_ADMIN_PORT=8161
     - WAIT_HOSTS=activemq:8161
     - WAIT_HOSTS_TIMEOUT=300
     - WAIT_SLEEP_INTERVAL=5
     - WAIT_HOST_CONNECT_TIMEOUT=5
    depends_on :
      - activemq
    networks:
      - news-tracker-network
  mongodb:
    image: mongo
    restart: on-failure
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=news-db
    networks:
      - news-tracker-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8089:8081
    networks:
      - news-tracker-network
  newsconsumer:
    image: erhancetin/k8s-news-tracker-consumer
    restart: on-failure
    container_name: newsconsumer
    environment:
      - ACTIVEMQ-HOST=activemq
      - ACTIVEMQ-PORT=61613
      - ACTIVEMQ-QUEUE-NAME=news-queue
      - MONGODB-HOST=mongodb
      - MONGODB-NAME=news-db
      - MONGODB-COLLECTION=article
      - WAIT_HOSTS=mongodb:27017,activemq:8161
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=5
    depends_on :
      - activemq
      - mongodb
    networks:
      - news-tracker-network
  newsapi:
    image: erhancetin/k8s-news-tracker-api
    restart: on-failure
    container_name: newsapi
    ports:
      - 8085:8080
    environment:
      - MONGODB-HOST=mongodb
      - MONGODB-NAME=news-db
      - MONGODB-PORT=27017
    networks:
      - news-tracker-network
networks:
  news-tracker-network:
    driver: "bridge"
