version: '3'
services:
  newsfe:
    container_name: news-tracker-fe
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_HOST_NAME=localhost
      - REACT_APP_API_HOST_PORT=8085
    stdin_open: true  
    networks:
      - news-tracker-network
networks:
  news-tracker-network:
    driver: "bridge"      