version: '3'
services:
  newsfe:
    container_name: news-tracker-fe
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NEWS_API_HOST_NAME=localhost
      - NEWS_API_HOST_PORT=8085
    stdin_open: true  #why : https://stackoverflow.com/questions/60801669/docker-compose-stops-immediately-after-starting-react-app-created-using-create-r
    networks:
      - news-tracker-network
networks:
  news-tracker-network:
    driver: "bridge"      