apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: newsproducer-cronjob
spec:
  schedule: "0/1 * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          name: newsproducer
          labels:
            app: newsproducer
            part-of: backend
            env: develop
        spec:
          restartPolicy: Never
          containers:
          - name: newsproducer
            image: erhancetin/k8s-news-tracker-job
            resources:
              limits:
                memory: "300Mi"
                cpu: "1"
              requests:
                memory: "200Mi"
                cpu: "0.5"
            imagePullPolicy: Always
            env:
              - name: ACTIVEMQ_ADMIN_LOGIN
                value: "admin"
              - name: NEWSAPI_AUTHORIZATION
                value: "1bb922b5221f42d2ad1fd8c9addfa531"
              - name: ACTIVEMQ_HOST
                value: "activemq-service"
              - name: ACTIVEMQ_PORT
                value: "61613"
              - name: ACTIVEMQ_QUEUE_NAME
                value: "news-queue"
              - name: ACTIVEMQ_USER_LOGIN
                value: "admin"
              - name: ACTIVEMQ_USER_PASSWORD
                value: "admin"
              - name: ACTIVEMQ_ADMIN_PORT
                value: "8161"
              - name: WAIT_HOSTS
                value:  "activemq-service:8161"
              - name: WAIT_HOSTS_TIMEOUT
                value: "300"
              - name: WAIT_SLEEP_INTERVAL
                value: "5"
              - name: WAIT_HOST_CONNECT_TIMEOUT
                value: "5"
