apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsmongdb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsmongdb
  template:
    metadata:
      name: newsmongdb
      labels:
        app: newsmongdb
        part-of: backend
        env: develop
    spec:
      containers:
        - name: newsmongodb
          image: mongo
          resources:
            limits:
              memory: "800Mi"
              cpu: "1"
            requests:
              memory: "500Mi"
              cpu: "0.5"
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: "news-db"

