apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsproducer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsproducer
  template:
    metadata:
      name: newsproducer
      labels:
        app: newsproducer
        part-of: backend
        env: develop
    spec:
      containers:
      - name: newsproducer
        image: erhancetin/k8s-news-tracker-job
        resources:
          limits:
            memory: "300Mi"
            cpu: "1"
          requests:
            memory: "200Mi"
            cpu: "0.5"
        imagePullPolicy: Always
        envFrom:
            - configMapRef:
                name: newsproducer-configmap  
            - secretRef:
                name: activemq-admin-password     