apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  MONGO_INITDB_DATABASE: "news-db"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    part-of: backend
spec:
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: newsmongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-stateful
spec:
  serviceName: "mongodb-service"
  replicas: 1
  selector:
    matchLabels:
      app: newsmongodb
  template:
    metadata:
      labels:
        app: newsmongodb
    spec:
      containers:
        - name: newsmongodb
          image: mongo
          resources:
            limits:
              memory: "300Mi"
              cpu: "0.5"
            requests:
              memory: "200Mi"
              cpu: "0.2"
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          envFrom:
            - configMapRef:
                name: mongodb-configmap


