apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodbexpress-configmap
data:
  ME_CONFIG_MONGODB_PORT: "27017"
  ME_CONFIG_MONGODB_SERVER: "mongodb-service"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodbexpress-service
  labels:
    part-of: backend
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: newsmongdbexpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsmongdbexpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsmongdbexpress
  template:
    metadata:
      name: newsmongdbexpress
      labels:
        app: newsmongdbexpress
        part-of: backend
        env: develop
    spec:
      containers:
        - name: newsmongodbexpress
          image: mongo-express
          resources:
            limits:
              memory: "100Mi"
              cpu: "0.5"
            requests:
              memory: "100Mi"
              cpu: "0.5"
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: mongodbexpress-configmap