apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    part-of: backend
spec:
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: newsmongodb