apiVersion: v1
kind: Service
metadata:
  name: mongodbexpress-service
  labels:
    part-of: backend
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: newsmongdbexpress
