apiVersion: v1
kind: Service
metadata:
  name: newstrackerfe-service
  labels:
    part-of: frontend
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: newstrackerfe