apiVersion: v1
kind: Service
metadata:
  name: newsproducer-service
  labels:
    part-of: backend
spec:
  type: ClusterIP
  ports:
    - port: 9999
      targetPort: 9999
  selector:
    app: newsproducer

