apiVersion: v1
kind: Service
metadata:
  name: newsconsumer-service
  labels:
    part-of: backend
spec:
  type: ClusterIP
  ports:
    - port: 9998
      targetPort: 9998
  selector:
    app: newsconsumer